export const ADD_ERROR="ADD_ERROR";
export const REMOVE_ERROR="REMOVE_ERROR";
export const SET_CURRENT_USER ="SET_CURRENT_USER";
export const LOAD_MESSAGES="LOAD_MESSAGES";
export const REMOVE_MESSAGE="REMOVE_MESSAGE";
export const UPDATE_MESSAGE="UPDATE_MESSAGE";
export const ADD_COMMENT="ADD_COMMENT";
export const REMOVE_COMMENT="REMOVE_COMMENT";
export const LOAD_USERS="LOAD_USERS";
export const LOAD_FRIENDS="LOAD_FRIENDS";

